version: '3'

services:
  jos3duardo:
    container_name: jos3duardo
    image: nginx
    restart: "unless-stopped"
    ports:
      - "9093:80"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - servidor-network

networks:
  servidor-network:
    external: true