version: "3"

services:
  jos3duardo:
    container_name: jos3duardo
    image: nginx
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`jos3duardo.com.br`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls.certresolver=letsencrypt"
      - "traefik.http.services.homepage.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
