version: "3"

services:
  jos3duardo:
    image: nginx
    restart: unless-stopped
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - traefik-net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.homepage.rule=Host(`jos3duardo.com.br`)"
        - "traefik.http.routers.homepage.entrypoints=websecure"
        - "traefik.http.routers.homepage.tls.certresolver=letsencrypt"
        - "traefik.http.services.homepage.loadbalancer.server.port=80"

networks:
  traefik-net:
    external: true
